### ISSUE TITLE
Publish build rules via npm

### ISSUE THREAD

**Issue by rzhw** [bazelbuild/rules_postcss#6]
Similar to the [TypeScript rules for Bazel](https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#installation), these build rules could be made available via npm.

Installing these build rules via npm avoids a Bazel workspace depending on these build rules having a package.json for rules_nodejs also depending on postcss, then having that version being hoisted up and interfering with the version used by these build rules.

**Comment by rzhw** [comment]
Also investigate version stamping (e.g. https://github.com/bazelbuild/bazelisk/commit/541325d070f320e78c2e30d1d6feeaba787c8162)

**Comment by marcus-sa** [comment]
So when will the rules be published to NPM?
If you need any help due to lack of time, I can create a PR.

**Comment by rzhw** [comment]
Hey, thanks for the offer! I've currently got pull request #42 sent out to get these rules ready for publishing to npm. It's going through some code review cycles there at the moment.

Once it lands and I've published to npm, I'll mark this issue as closed.

**Comment by marcus-sa** [comment]
Sure, feel free to ping me otherwise, I use Bazel for everything 😉

**Comment by rzhw** [comment]
0.5.0 is now available at https://www.npmjs.com/package/@bazel/postcss.
